#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def render_header(gains: dict) -> str:
    inner = gains["inner"]
    outer = gains["outer"]
    meta = gains.get("meta", {})
    units = meta.get("units", {})

    unit_lines = [
        f"// outer_error: {units.get('outer_error', 'n/a')}",
        f"// outer_output: {units.get('outer_output', 'n/a')}",
        f"// inner_error: {units.get('inner_error', 'n/a')}",
        f"// inner_output: {units.get('inner_output', 'n/a')}",
        f"// outer_integral_state: {units.get('outer_integral_state', 'n/a')}",
        f"// inner_integral_state: {units.get('inner_integral_state', 'n/a')}",
    ]

    return f"""#pragma once

namespace bb {{
namespace generated {{

// Auto-generated by model/first_principles/export_gains.py
{'\n'.join(unit_lines)}

constexpr float kInnerKp = {inner['kp']:.6f}f;
constexpr float kInnerKi = {inner['ki']:.6f}f;
constexpr float kInnerKd = {inner['kd']:.6f}f;
constexpr float kInnerIMin = {inner['i_min']:.6f}f;
constexpr float kInnerIMax = {inner['i_max']:.6f}f;
constexpr float kInnerOutMin = {inner['out_min']:.6f}f;
constexpr float kInnerOutMax = {inner['out_max']:.6f}f;

constexpr float kOuterKp = {outer['kp']:.6f}f;
constexpr float kOuterKi = {outer['ki']:.6f}f;
constexpr float kOuterKd = {outer['kd']:.6f}f;
constexpr float kOuterIMin = {outer['i_min']:.6f}f;
constexpr float kOuterIMax = {outer['i_max']:.6f}f;
constexpr float kOuterOutMin = {outer['out_min']:.6f}f;
constexpr float kOuterOutMax = {outer['out_max']:.6f}f;

}}  // namespace generated
}}  // namespace bb
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Export controller gains to firmware header")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(__file__).with_name("controller_initial_gains.json"),
        help="Path to gains JSON",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[2]
        / "firmware"
        / "include"
        / "generated"
        / "controller_gains.h",
        help="Output header path",
    )
    args = parser.parse_args()

    with args.input.open("r", encoding="utf-8") as f:
        gains = json.load(f)

    header = render_header(gains)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8")

    print("Exported:", args.output)


if __name__ == "__main__":
    main()
