#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def render_header(gains: dict) -> str:
    physical = gains["physical_pid"]
    pid = gains["pid"]
    meta = gains.get("meta", {})
    units = meta.get("units", {})

    unit_lines = [
        f"// physical_error: {units.get('physical_error', 'n/a')}",
        f"// physical_output: {units.get('physical_output', 'n/a')}",
        f"// step_error: {units.get('step_error', 'n/a')}",
        f"// step_output: {units.get('step_output', 'n/a')}",
        f"// physical_kp: {units.get('physical_kp', 'n/a')}",
        f"// physical_ki: {units.get('physical_ki', 'n/a')}",
        f"// physical_kd: {units.get('physical_kd', 'n/a')}",
        f"// kp: {units.get('kp', 'n/a')}",
        f"// ki: {units.get('ki', 'n/a')}",
        f"// kd: {units.get('kd', 'n/a')}",
    ]

    return f"""#pragma once

namespace bb {{
namespace generated {{

// Auto-generated by model/first_principles/export_gains.py
{'\n'.join(unit_lines)}

constexpr float kReferencePhysicalPidKpRadPerM = {physical['kp']:.6f}f;
constexpr float kReferencePhysicalPidKiRadPerMSec = {physical['ki']:.6f}f;
constexpr float kReferencePhysicalPidKdRadSecPerM = {physical['kd']:.6f}f;

constexpr float kReferencePidKpStepsPerCm = {pid['kp']:.6f}f;
constexpr float kReferencePidKiStepsPerCmSec = {pid['ki']:.6f}f;
constexpr float kReferencePidKdStepsSecPerCm = {pid['kd']:.6f}f;
constexpr float kReferencePidOutMinSteps = {gains['out_min_steps']:.6f}f;
constexpr float kReferencePidOutMaxSteps = {gains['out_max_steps']:.6f}f;

}}  // namespace generated
}}  // namespace bb
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Export controller gains to firmware header")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(__file__).with_name("controller_initial_gains.json"),
        help="Path to gains JSON",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[2]
        / "firmware"
        / "include"
        / "generated"
        / "controller_gains.h",
        help="Output header path",
    )
    args = parser.parse_args()

    with args.input.open("r", encoding="utf-8") as f:
        gains = json.load(f)

    header = render_header(gains)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8")

    print("Exported:", args.output)


if __name__ == "__main__":
    main()
